# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MyWallet' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyWallet
  pod 'MMDrawerController', '~> 0.5.7'

  target 'MyWalletTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyWalletUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
